# Generated by Django 5.1.4 on 2025-04-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created',
        ),
        migrations.AddField(
            model_name='task',
            name='dayin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
